# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'activerecord', require: 'active_record'
gem 'irb'
gem 'rake'
gem 'sqlite3'
gem 'zeitwerk'
